### ISSUE TITLE
morning-session-group-aku-mphatso-atilla-251

### ISSUE THREAD

**Issue by aakbarkhan** [Lichapa/Leaderboard#3]
## Hi,  @Lichapa  👋 

You've done a really nice job.

## To highlight 👏👏
- ✔Commit messages is meaningful.
- ✔ Pull request title is discriptive.
- ✔ .gitignore file used it properly.
- ✔ README is descriptive.
- ✔ Gitflow is correctly setup.
- ✔[JavaScript best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
- ✔[DRY, KISS, and YAGNI](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/lesson_DRY_KISS_YAGNI.md) rules.
- ✔[HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- ✔  Linter set up correctly

**Comment by Lichapa** [comment]
Thank you very much.
